# Generated by Django 5.2.6 on 2025-09-27 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0002_document_content_text_document_editor_settings_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="draft_content",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Draft content for auto-save (not yet published)",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="has_unsaved_changes",
            field=models.BooleanField(
                default=False,
                help_text="Whether there are unsaved changes in draft_content",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="last_auto_save",
            field=models.DateTimeField(
                blank=True, help_text="Timestamp of last auto-save", null=True
            ),
        ),
    ]
