# Generated by Django 5.2.6 on 2025-10-15 14:21

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aidocumentmetadata',
            name='embedding_vector',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=3584, help_text='Document embedding vector', null=True),
        ),
    ]
