# Generated by Django 5.2.6 on 2025-10-16 06:10

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_services', '0002_alter_aidocumentmetadata_embedding_vector'),
        ('documents', '0003_document_draft_content_document_has_unsaved_changes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('feedback_type', models.CharField(choices=[('summary_quality', 'Summary Quality'), ('tag_relevance', 'Tag Relevance'), ('search_relevance', 'Search Relevance'), ('content_type_accuracy', 'Content Type Accuracy'), ('processing_speed', 'Processing Speed'), ('overall_satisfaction', 'Overall Satisfaction')], max_length=50)),
                ('rating', models.IntegerField(choices=[(1, 'Very Poor'), (2, 'Poor'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')])),
                ('comment', models.TextField(blank=True, help_text='Optional detailed feedback')),
                ('feedback_data', models.JSONField(blank=True, default=dict, help_text='Specific feedback details (e.g., which tags were wrong)')),
                ('model_version', models.CharField(blank=True, max_length=50)),
                ('processing_time_ms', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ai_metadata', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='ai_services.aidocumentmetadata')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_feedback', to='documents.document')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_feedback', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_user_feedback',
                'indexes': [models.Index(fields=['user', 'feedback_type'], name='idx_feedback_user_type'), models.Index(fields=['document', 'feedback_type'], name='idx_feedback_doc_type'), models.Index(fields=['feedback_type', 'rating'], name='idx_feedback_type_rating'), models.Index(fields=['created_at'], name='idx_feedback_created')],
            },
        ),
    ]
