# Generated by Django 5.2.6 on 2025-10-16 07:12

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_services', '0003_userfeedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aidocumentmetadata',
            name='embedding_vector',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=4096, help_text='Document embedding vector generated by qwen3-embedding:8b', null=True),
        ),
    ]
